syncs:
  - repos:
      - deltaprojects/hello-kubernetes
      - deltaprojects/intranet
      - deltaprojects/delta-dashkiosk-k8s
      - deltaprojects/kafka-manager-k8s
      - deltaprojects/github-actions-dashboard
      - deltaprojects/lightair-k8s
      - deltaprojects/buildkit-k8s
      - deltaprojects/httpbin-k8s
      - deltaprojects/delta-validator
    files:
      - src: workflows/tilt.yaml
        dest: .github/workflows/tilt.yaml
      - src: workflows/auto-merge-syncs.yaml
        dest: .github/workflows/auto-merge-syncs.yaml
