
on: pull_request

jobs:
  merge:
    name: "Auto merge workflow syncs"

    runs-on: "ubuntu-latest"

    if: >
      github.event_name == 'pull_request' &&
      github.event.pull_request.draft == false && (
        github.event.action == 'opened' ||
        github.event.action == 'reopened' ||
        github.event.action == 'synchronize'
      ) && (
        github.actor == 'gh-file-sync[bot]'
      )

    steps:
      - name: Merge pull request for ${{ github.event.client_payload.ReleaseBranchName }}
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.pulls.merge({
              merge_method: "rebase",
              owner: context.repo.owner,
              pull_number: context.payload.pull_request.number,
              repo: context.repo.repo,
            })

      - name: Delete merged pull request branch
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const refExists = await github.git.getRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "heads/${{ github.head_ref }}",
            }).then(() => true, error => {
              if (error.status === 404) return false
              throw error
            })

            if (refExists) {
              await github.git.deleteRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: "heads/${{ github.head_ref }}",
              })
            }
