on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    # git tag v1.0.2
    # git push origin --tags
    tags:
    - "v*"
    paths-ignore:
    - 'docs/**'
    - '**/README.md'
    - '**/LICENSE'
    - '**/.gitignore'

jobs:
  build-and-deploy:
    name: build and deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      # Create a access token in docker hub -> settings -> security.
      # Create two GitHub secrets DOCKER_HUB_USERNAME and DOCKER_HUB_ACCESS_TOKEN.
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Install kube tools
      env: 
        # renovate: datasource=github-releases depName=tilt-dev/tilt
        TILT_VERSION: 'v0.19.7'
        # renovate: datasource=github-releases depName=rancher/cli
        RANCHER_VERSION: 'v2.4.12'
      uses: yokawasa/action-setup-kube-tools@v0.8.0
      with:
        tilt: ${{ env.TILT_VERSION }}
        rancher: ${{ env.RANCHER_VERSION }}
        setup-tools: |
          tilt
          rancher
          yq

    - name: Download BuildKit CLI for kubectl
      uses: engineerd/configurator@v0.0.8
      with:
        name: kubectl-build
        pathInArchive: kubectl-build
        fromGitHubReleases: true
        repo: vmware-tanzu/buildkit-cli-for-kubectl
        includePrereleases: true
        token: ${{ secrets.GITHUB_TOKEN }}
        urlTemplate: https://github.com/vmware-tanzu/buildkit-cli-for-kubectl/releases/download/{{version}}/linux-{{version}}.tgz
        version: latest

    # - name: configure kubectl from secret
    #   shell: bash
    #   run: |
    #     if ! [[ -z "${{ secrets.KUBE_CONFIG }}" ]]; then
    #       mkdir -p ${HOME}/.kube/ && echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > ${HOME}/.kube/config
    #     fi

    - name: configure kubectl from Rancher API key
      shell: bash
      run: |
        if ! [[ -z "${{ secrets.RANCHER_CONTEXT }}" || -z "${{ secrets.RANCHER_CONTEXT }}" || -z "${{ secrets.RANCHER_URL }}" ]]; then
          rancher login --context ${{ secrets.RANCHER_CONTEXT }} --token ${{ secrets.RANCHER_TOKEN }} ${{ secrets.RANCHER_URL }}
          mkdir -p ${HOME}/.kube
          rancher kubectl config view --minify --raw > ${HOME}/.kube/config
        else
          echo needs secrets RANCHER_CONTEXT, RANCHER_CONTEXT and RANCHER_URL
          exit 1
        fi

    - name: set RELEASE_TAG variable.
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
      # This does the same:
      # if: github.event_name == 'push' && github.event.ref_type == 'tag' && startsWith(github.event.ref, 'v')
      # github.ref == 'refs/tags/v1.2.5' or 'refs/heads/feature-branch-1'
      # github.event.ref == 'v1.2.5' or 'feature-branch-1'
      shell: bash
      run: echo "RELEASE_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: build, push and deploy
      shell: bash
      run: tilt ci
