name: Tilt
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main
      - master
    # git tag v1.0.2
    # git push origin --tags
    tags:
    - "v*"
    paths-ignore:
    - 'docs/**'
    - '**/README.md'
    - '**/LICENSE'
    - '**/.gitignore'

# Concurrency group to prevent concurrent runs
concurrency:
  group: '${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'

jobs:
  tilt:
    name: Initialize and Execute Tilt
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}
    steps:
      # If not public
      # - uses: actions/checkout@v2
      #   with:
      #     repository: deltaprojects/action-ci-cd
      #     path: auth-action
      #     token: XXX
      # - uses: ./auth-action/workflows/auth
      # if public
      - uses: deltaprojects/action-tilt-ci-cd/workflows/auth@master
        with:
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
          CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RANCHER_CONTEXT: ${{ secrets.RANCHER_CONTEXT }}
          RANCHER_URL: ${{ secrets.RANCHER_URL }}
          RANCHER_TOKEN: ${{ secrets.RANCHER_TOKEN }}

      - name: Execute Tilt
        shell: bash
        run: tilt ci
