name: Workflow Sync

on:
  workflow_dispatch:
  push:
    branches:
      - $default-branch
  # pull_request:
  #   branches:
  #     - $default-branch

jobs:
  file-syncs:
    runs-on: ubuntu-latest
    steps:
      - name: Running Workflow Sync
        uses: 'jetersen/ghaction.file.sync@v1'
        with:
          appId: ${{ secrets.FILE_SYNC_APP_ID }}
          privateKey: ${{ secrets.FILE_SYNC_APP_PEM }}
